// ============================================================
// GSpaceAi — Hardcoded Q1–Q5
// These questions are always shown first, in order.
// Q6–Q10 are generated by Gemini after Q5 is answered.
// ============================================================

import type { GeneratedQuestion } from "./types";

export const HQ1: GeneratedQuestion = {
  id: "hq1",
  question: "Is your business primarily service-based or product-based?",
  type: "single_select",
  options: [
    { id: "hq1_a", label: "Service-based — I sell expertise, time, or outcomes" },
    { id: "hq1_b", label: "Product-based — I sell physical or digital products" },
  ],
};

export const HQ2_SERVICE: GeneratedQuestion = {
  id: "hq2",
  question: "What type of services do you offer?",
  type: "single_select",
  options: [
    { id: "hq2_a", label: "Consulting or coaching" },
    { id: "hq2_b", label: "Home or field services" },
    { id: "hq2_c", label: "Health, wellness, or fitness" },
    { id: "hq2_d", label: "Legal, financial, or accounting" },
    { id: "hq2_e", label: "Creative, marketing, or design" },
    { id: "hq2_f", label: "Other professional services" },
  ],
};

export const HQ2_PRODUCT: GeneratedQuestion = {
  id: "hq2",
  question: "What type of products do you sell?",
  type: "single_select",
  options: [
    { id: "hq2_a", label: "Physical retail or e-commerce" },
    { id: "hq2_b", label: "Food or beverage" },
    { id: "hq2_c", label: "Wholesale or distribution" },
    { id: "hq2_d", label: "Digital products or software" },
    { id: "hq2_e", label: "Manufacturing or fabrication" },
    { id: "hq2_f", label: "Other products" },
  ],
};

// Q3 is exempt from the 3–5 option limit — tool inventory
export const HQ3: GeneratedQuestion = {
  id: "hq3",
  question: "Which of these tools does your business currently pay for?",
  type: "multi_select",
  options: [
    { id: "hq3_01", label: "Calendly" },
    { id: "hq3_02", label: "HoneyBook" },
    { id: "hq3_03", label: "QuickBooks or FreshBooks" },
    { id: "hq3_04", label: "Slack" },
    { id: "hq3_05", label: "Zoom" },
    { id: "hq3_06", label: "Dropbox or Box" },
    { id: "hq3_07", label: "Mailchimp or Constant Contact" },
    { id: "hq3_08", label: "Monday.com, Asana, or ClickUp" },
    { id: "hq3_09", label: "DocuSign" },
    { id: "hq3_10", label: "Canva" },
    { id: "hq3_11", label: "Salesforce or HubSpot" },
    { id: "hq3_12", label: "Notion or Airtable" },
    { id: "hq3_13", label: "ServiceTitan or Jobber" },
    { id: "hq3_14", label: "Stripe or Square" },
    { id: "hq3_15", label: "Other tools not listed" },
  ],
};

export const HQ4: GeneratedQuestion = {
  id: "hq4",
  question: "What's your first name?",
  type: "text_input",
  options: [],
  placeholder: "Enter your first name",
};

export const HQ5: GeneratedQuestion = {
  id: "hq5",
  question: "And what's the name of your business?",
  type: "text_input",
  options: [],
  placeholder: "Enter your business name",
};

// Default initial set (Q2 starts as service variant; swaps to product if Q1 answer contains "Product")
export const HARDCODED_QUESTIONS: GeneratedQuestion[] = [HQ1, HQ2_SERVICE, HQ3, HQ4, HQ5];
